### ISSUE TITLE
Finalize topic browsing bar

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#171]
![bildschirmfoto 2015-05-26 um 09 22 26](https://cloud.githubusercontent.com/assets/384894/7807129/05a4a3c6-0389-11e5-9be5-f6a21f53427b.png)

Two things need still to  be done:
- [x] Hard-code the 16 top level topic terms
- [x] Add filter by language buttons below flags
- [x] Fix: Links on groups pages http://data.opendevelopmentmekong.net/group

**Comment by acorbi** [comment]
@DBishton Is the definition of the taxonomy finalized? Do we know the final list of 16 top-tier taxonomic terms that we are going to be using? I need the final list for implementing this Issue

**Comment by DBishton** [comment]
Hi @acorbi, see below. There are now 17.

Agriculture & fishing
Aid and development
Economy and commerce
Energy
Environment and natural resources 
Extractive industries
Government
Industry
Infrastructure
Labor
Land
Law & judiciary
Population and censuses
Science and technology
Urban administration and development
Social development

**Comment by acorbi** [comment]
@DBishton There are only 16 on that list
