### ISSUE TITLE
ODC logo is slightly off throughout CKAN

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/ckanext-odm_theme#192]
The ODC logo in CKAN seems to be a bit off in my browsers (Chrome and Safari). Here is a sample:
https://data.opendevelopmentmekong.net/organization

![issue with ckan](https://cloud.githubusercontent.com/assets/4859982/8198452/a9446568-14d0-11e5-80fe-f66f85526086.png)

**Comment by acorbi** [comment]
@Numnov  This is a weird one.... Sometimes I had similar artifacts, or even some logos not being loading...

**Comment by Numnov** [comment]
@acorbi, I think we can hold off on focusing on this. It seems to only come up at random times on certain computers.

**Comment by acorbi** [comment]
Yeah, let's close it. Re-open if necessary...
