### ISSUE TITLE
Different titles of items in for source section of in CKAN library records

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/ckanext-odm_theme#201]
When the data entry experts open the resources for certain library items, it shows the title and summary of a different library item. Previewing or downloading also takes me to this incorrect item. However, when I go to 'edit' (to replace the pdf, title and summary with the correct one), it has switched back to the pdf, title and summary it should be. Note that this happens occasionally. Not every record is like this. It seems to be some type of bug and hopefully not human error when inputing the meta data.

An example of this can be seen here:

https://data.opendevelopmentmekong.net/library/adolescents-and-youth-in-viet-nam-reproductive-health-and-education

and here:

 https://data.opendevelopmentmekong.net/library_record/greater-mekong-subregion-working-group-on-agriculture-workshop

**Comment by acorbi** [comment]
@Numnov Fixed. There was a Bug that provoqued that the title and description on certain resources would get the value of a diferent resource, visited by the user sometime before.

Now this shouldn't happen again and I have corrected those 2 resources you listed but please mind that this could have happened in other datasets/resources, in case other such inconsistencies are found, please fix them directly.
