### ISSUE TITLE
CKAN description for this record seems to run out of the box. 

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/ckanext-odm_theme#203]
![screen shot 2015-06-25 at 4 38 49 pm](https://cloud.githubusercontent.com/assets/4859982/8351719/9eac4b0e-1b59-11e5-973f-e104f4d7bce6.png)

See link:

https://data.opendevelopmentmekong.net/library_record/imperiled-giant-fish-mainstream-dams-lower-mekong-basin-status-threats-mitigation

**Comment by acorbi** [comment]
Fixed. There was some hidden characters in the description that made it render so strange. I just edited the text and saved the dataset.
