### ISSUE TITLE
Header tags for top-level taxonomy tags appear non-functional

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/ckanext-odm_theme#204]
![image](https://cloud.githubusercontent.com/assets/1206387/8350659/9a5dc29c-1b51-11e5-93b5-786ad3ce12e6.png)

For example, clicking on Energy should return a number of records, including this one:
https://data.opendevelopmentmekong.net/library/water-food-energy-nexus

But no results are returned:

![image](https://cloud.githubusercontent.com/assets/1206387/8351782/fdbfe380-1b59-11e5-9264-0dbde4d23b63.png)

**Comment by acorbi** [comment]
@DBishton This has being now fixed and already deployed on https://data.opendevelopmentmekong.net. As you can see now not only the header tags work as expected, but also a list of tags is presented on the left sidebar of screens with dataset results. on the This increases browseability considerably!!!

![bildschirmfoto 2015-06-30 um 18 43 03](https://cloud.githubusercontent.com/assets/384894/8436346/f6a7fad6-1f57-11e5-9a2f-29a0b5512fd8.png)
