### ISSUE TITLE
Adding/updating topic tags for datasets don't appear to save

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/ckanext-odm_theme#217]
Hi @acorbi and @Huyeng,

This afternoon Kate created this dataset: https://data.opendevelopmentmekong.net/dataset/the-state-of-the-world-s-children-report-2015-statistical-tables 

When reviewing it, I asked her why she didn't add tags. She said she had, but they disappeared, or didn't save. I then tried to add some myself by clicking 'Manage', and upon saving, the change did not seem to be reflected.

**Comment by acorbi** [comment]
@DBishton @Kate indeed seems that Tag information is not getting stored for "normal" datasets BUT it is working for library records. I am going to check it and deliver a fix. 

In the meanwhile please track newly created datasets...
