### ISSUE TITLE
The tag bubbles of each datasource is 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_theme#220]
The link broken, When click on the taxonomy name bubble under the data source name.
Those tag/taxonomy bubbles link should contain variables "vocab_taxonomy=" not "tag="

Example page: https://data.opendevelopmentmekong.net/library/the-population-and-housing-census-of-myanmar
![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/10040150/47443854-6203-11e5-99ad-ceba3ac226c4.jpg)

**Comment by acorbi** [comment]
Implement taxonomy filtering using tag= and not vocab_taxonomy=. The pother way around.
