### ISSUE TITLE
[UI] Should the library be removed from groups

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#27]
Since we have a separate section for the library contents, should it be removed from the list of groups http://data.opendevelopmentmekong.net/group as it has been from the list of organizations http://data.opendevelopmentmekong.net/organization?

**Comment by DBishton** [comment]
Hi Alex,

Thanks for drawing attention to this. My initial reaction would be 'yes' -- for consistency.

It raises a larger question for me though, about how we expect users to interact with the library content. Will there be 1) a dedicated, separate section for library on the front end, or 2) would we expect them to view these items in CKAN? My assumption is 1), but if it's 2) then we need a way to indicate library items to a user -- which could be group, or organization, or another method. I'd like to hear your thoughts.

**Comment by acorbi** [comment]
@DBishton Library records will be mainly maintained in CKAN. Editors can link Library records from wordpress and it would be thinkable to have special WP page dedicated to present the library records.
Closing this Issue
