### ISSUE TITLE
[UI] Implement advanced form controls

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#33]
Currently, the need for a date picker and a dropdown box with limited input has been identified for extending the funcitonalities on the Metadata template and Library template

**Comment by acorbi** [comment]
Also, define final order of the fields and which of them are mandatory or not.

**Comment by Numnov** [comment]
Can we also include the following: a) a dropdown menu for the language field with short terms for the languages (en, km etc). b) increase the size of the box for the sources field, this box should be able to include space for at least 9 sources and potentially capability to upload a document that lists additional sources. d) For the license fields, let remove all options except the licenses listed in the Wiki.

**Comment by acorbi** [comment]
d) has been implemented via https://github.com/OpenDevelopmentMekong/ckanext-odm_theme/commit/cb25128415d392c5b8b791635689a890d6d23c19
