### ISSUE TITLE
Final metadata form templates

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#38]
The final list of metadata fields for normal datasets and library records should be defined. Order and mandatory fields should be speficied.

**Comment by Numnov** [comment]
Alex, here agreed upon mandatory fields from the metadata template as agreed upon by ODC, Dan and I:
Title, Description,Format,Language, Date Created, Date Uploaded, Date Modified, Temporal Range, Processes, Sources and Contact 

Please note, for all the date fields can you create the pop-up calendar feature.

**Comment by acorbi** [comment]
Just for reference, implementing the pop-up calendar feature is a task belonging to the milestone v1.0 https://github.com/OpenDevelopmentMekong/ckanext-odm_theme/issues/33
