### ISSUE TITLE
Rename CKAN organizations

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/ckanext-odm_theme#49]
Please rename the current organizations in the OD CKAN system as described below. Please use your discretion -- full titles are preferred, but shorter ones may present better. Thanks!

ODM Mekong > Open Development Mekong or OD Mekong

ODM Cambodia > Open Development Cambodia or OD Cambodia

ODM Vietnam > Open Development Vietnam or OD Vietnam

ODM Thailand > Open Development Thailand or OD Thailand

ODM Myanmar > Open Development Myanmar or OD Myanmar

**Comment by acorbi** [comment]
Fixed, check http://data.opendevelopmentmekong.net/organization
