### ISSUE TITLE
[import_from_geoserver] Add additional representation formats for maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#64]
_From @acorbi on March 19, 2015 7:7_

Modify the script to import also other representation formats for the map layers, for users to download:
- Shapefile (SHP)

_Copied from original issue: OpenDevelopmentMekong/ckanext-odm_utils#81_

**Comment by acorbi** [comment]
@Huyeng Can you label this Issue with the priority (p1,p2 or p3) you think it deservers? Also, Any other formats to Add?

**Comment by Huyeng** [comment]
KML and CSV are additional formats that need for the users to download.
However, the CSV files that generated from the geoserver has some format issue.

**Comment by acorbi** [comment]
@Huyeng I have checked and it would be possible to download from geoserver CSV and KML representations of the layers. However, the size of the files might be an Issue. Certain CSV are ~5MB big...
