### ISSUE TITLE
[import_from_geoserver] Raster layers not getting imported

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#66]
_From @acorbi on March 12, 2015 9:4_

Raster layers such as those depicted below are not getting imported into CKAN. Script should be modified so a dataset is created with PNG and PDF resources ( no GEOJSON ).
![bildschirmfoto 2015-03-12 um 10 02 32](https://cloud.githubusercontent.com/assets/384894/6614877/edf7ff68-c89e-11e4-90d1-ee8da3854f6e.png)

_Copied from original issue: OpenDevelopmentMekong/ckanext-odm_utils#79_

**Comment by acorbi** [comment]
Raster layers are not being listed when calling rest api on http://geoserver.opendevelopmentmekong.net/geoserver/rest/layers.json
@Huyeng any ideas on how to get the raster layers from the API?

**Comment by Huyeng** [comment]
@Alex, with GeoWebCache, this link below will list all the map layers both vector and raster layer types, but I don't know, it is helpful for you ro not. Please have a look. 
http://geoserver.opendevelopmentmekong.net/geoserver/gwc/rest/layers

**Comment by acorbi** [comment]
Thanks @Huyeng , this is indeed helpful!
