### ISSUE TITLE
Remove Law PDFs on pre-production

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#92]
Since Issue #65 has been fixed, PDF files are now stored locally and datasets from the laws group does not link anymore to files on cambodia.opendevelopment.net. Therefore, PDFs found on http://cambodia.opendevelopmentmekong.net/wp-content/blogs.dir/2/download/law/ can be completely removed.

**Comment by acorbi** [comment]
@Huyeng can we proceed with this? Or do you need those PDF file for something?

**Comment by Huyeng** [comment]
Well, if all the dataset is stored in the CKAN, so the directory of law should remove, but the frontend of law page needs to be updated, but not now, as it was temporarily pointed to the CKAN..

**Comment by acorbi** [comment]
Ok, so there is no application, page or anything pointing at those files on the wordpress site, correct?
Yes, the new implementations ( law page on opendevelopmentmekong.net ) should be modified in order to pull the PDFs from CKAN.
From now on, all PDFs for laws will be stored there...
mercredi, 22 avril 2015, 00:23PM +02:00 de Huyeng <notifications@github.com>:

**Comment by acorbi** [comment]
Done
