### ISSUE TITLE
Errored resources imported from certain map layers

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#98]
With import_from_geoserver.py script some layers get correctly imported but feature error on the resources.
Analize difference between these and those correctly imported and find fix.

Example: http://data.opendevelopmentmekong.net/dataset/map_geology_2006

**Comment by acorbi** [comment]
Tried to download Open Layers and/or PNG representation of some of the erratic layers on http://geoserver.opendevelopmentmekong.net/geoserver/web/ and got the following message returned for by the server.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://geoserver.opendevelopmentmekong.net:80/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.RuntimeException
null
Provided file does not exist or is a directory or is not readable!
Provided file does not exist or is a directory or is not readable!
</ServiceException></ServiceExceptionReport>
```

**Comment by acorbi** [comment]
@Huyeng any updates on the re-deployment of geoserver? Is this inconsistency solved? Can we run the import scripts again and close this?

**Comment by Huyeng** [comment]
@Alex, thanks for informing me these errors. I have already fixed theme. The problem  caused by not updating the DB information and the raster file name is also changed. 
Please check, and let me know if any error exists. Please close the issue if every thing is ok.

**Comment by acorbi** [comment]
Great, I will check it today!

**Comment by acorbi** [comment]
This Issue is now fixed
